### ISSUE TITLE
when i try to connect i get an error

### ISSUE THREAD

**Issue by FireC123** [hellomouse/node-omegle#1]
Unhandled rejection RequestError: Error: getaddrinfo ENOTFOUND undefined.omegle.com undefined.omegle.com:80
    at new RequestError (C:\Users\******\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\******\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\******\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\******\node_modules\request\request.js:187:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\******\node_modules\request\request.js:813:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by iczero** [comment]
Are you calling connect after the `ready` event fires?

**Comment by iczero** [comment]
Sorry about that, I completely forgot about the `ready` event when writing the docs
